import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const db=createClient('https://lebuvkypywblwrjhabpn.supabase.co','sb_publishable_CwGqVxwacoCk_JE6s-ziig_noJ0qf0u');
const $=s=>document.querySelector(s), view=$('#view'), dialog=$('#product-dialog');let me, categories=[];
const money=n=>new Intl.NumberFormat('ar-SA',{style:'currency',currency:'SAR',maximumFractionDigits:0}).format(n||0);
$('#today').textContent=new Intl.DateTimeFormat('ar-SA',{dateStyle:'full'}).format(new Date());
async function start(){let {data:{session}}=await db.auth.getSession();if(!session)return;let {data:p}=await db.from('profiles').select('*').eq('id',session.user.id).maybeSingle();if(!p){$('#auth-msg').textContent='الحساب موجود، لكن لم تُمنح له صلاحية بعد. راجع خطوة تعيين المدير في ملف schema.sql.';return}me=p;$('#auth').hidden=true;$('#app').hidden=false;$('#role').textContent=p.full_name||p.role;load('dashboard')}
$('#login').onsubmit=async e=>{e.preventDefault();$('#auth-msg').textContent='جارٍ التحقق...';let f=new FormData(e.target),{error}=await db.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});$('#auth-msg').textContent=error?'بيانات الدخول غير صحيحة.': '';if(!error)start()};$('#signout').onclick=async()=>{await db.auth.signOut();location.reload()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>load(b.dataset.page));
async function load(page){document.querySelector('nav .active').classList.remove('active');$(`nav [data-page="${page}"]`).classList.add('active');$('#page-title').textContent={dashboard:'نظرة عامة',products:'المنتجات',orders:'الطلبات',team:'فريق العمل'}[page];if(page==='dashboard')return dashboard();if(page==='products')return products();if(page==='orders')return orders();team()}
async function dashboard(){let [{count:pc},{count:oc},{data:orders}]=await Promise.all([db.from('products').select('*',{count:'exact',head:true}),db.from('orders').select('*',{count:'exact',head:true}),db.from('orders').select('total,status')]);let sales=(orders||[]).filter(x=>x.status!=='cancelled').reduce((a,x)=>a+Number(x.total),0);view.innerHTML=`<div class="stats"><article><span>المنتجات</span><b>${pc||0}</b><small>قطعة في الكتالوج</small></article><article><span>الطلبات</span><b>${oc||0}</b><small>كل الطلبات</small></article><article><span>المبيعات</span><b>${money(sales)}</b><small>الإجمالي المسجل</small></article></div><section class="welcome"><p>مرحباً ${me.full_name||''} ✦</p><h2>كل تفاصيل متجرك<br>بين يديك.</h2><button onclick="document.querySelector('[data-page=products]').click()">إضافة أول منتج ←</button></section>`}
async function products(){let [{data:items},{data:cats}]=await Promise.all([db.from('products').select('*,categories(name)').order('created_at',{ascending:false}),db.from('categories').select('*').order('name')]);categories=cats||[];view.innerHTML=`<div class="toolbar"><input id="filter" placeholder="ابحث باسم المنتج..."><button class="primary" id="new-product">+ إضافة منتج</button></div><div class="table-wrap"><table><thead><tr><th>المنتج</th><th>التصنيف</th><th>السعر</th><th>المخزون</th><th>الحالة</th><th></th></tr></thead><tbody>${(items||[]).map(x=>`<tr data-id="${x.id}"><td><b>${x.name}</b><small>${x.slug}</small></td><td>${x.categories?.name||'—'}</td><td>${money(x.sale_price||x.price)}</td><td>${x.stock}</td><td><i class="${x.is_active?'on':'off'}">${x.is_active?'ظاهر':'مخفي'}</i></td><td><button class="edit">تعديل</button></td></tr>`).join('')||'<tr><td colspan="6" class="none">لا توجد منتجات حتى الآن. أضف أول منتج.</td></tr>'}</tbody></table></div>`;$('#new-product').onclick=()=>openProduct();document.querySelectorAll('.edit').forEach((b,i)=>b.onclick=()=>openProduct(items[i]));$('#filter').oninput=e=>document.querySelectorAll('tbody tr').forEach(r=>r.hidden=!r.innerText.includes(e.target.value))}
function openProduct(p={}){$('#modal-title').textContent=p.id?'تعديل المنتج':'منتج جديد';let f=$('#product-form');f.reset();Object.entries(p).forEach(([k,v])=>{if(f[k])f[k].type==='checkbox'?f[k].checked=v:f[k].value=Array.isArray(v)?v.join(','):v??''});$('#product-category').innerHTML='<option value="">اختر التصنيف</option>'+categories.map(c=>`<option value="${c.id}" ${p.category_id===c.id?'selected':''}>${c.name}</option>`).join('');dialog.showModal()}
$('#product-form').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),o=Object.fromEntries(f);o.price=+o.price;o.stock=+o.stock;o.sale_price=o.sale_price?+o.sale_price:null;o.sizes=o.sizes?o.sizes.split(',').map(x=>x.trim()):[];o.is_active=f.get('is_active')==='on';let error=o.id?(await db.from('products').update(o).eq('id',o.id)).error:(await db.from('products').insert(o)).error;if(error)return alert(error.message);dialog.close();products()};
async function orders(){let {data}=await db.from('orders').select('*').order('created_at',{ascending:false});view.innerHTML=`<div class="table-wrap"><table><thead><tr><th>رقم الطلب</th><th>العميل</th><th>الإجمالي</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td>#${x.id.slice(0,7)}</td><td>${x.customer_name||'—'}<small>${x.customer_phone||''}</small></td><td>${money(x.total)}</td><td><select class="order-status" data-id="${x.id}">${['new','confirmed','processing','shipped','delivered','cancelled'].map(s=>`<option ${s===x.status?'selected':''} value="${s}">${({new:'جديد',confirmed:'مؤكد',processing:'قيد التجهيز',shipped:'تم الشحن',delivered:'تم التسليم',cancelled:'ملغي'})[s]}</option>`).join('')}</select></td><td>${new Date(x.created_at).toLocaleDateString('ar-SA')}</td></tr>`).join('')||'<tr><td colspan="5" class="none">لا توجد طلبات حتى الآن.</td></tr>'}</tbody></table></div>`;document.querySelectorAll('.order-status').forEach(s=>s.onchange=()=>db.from('orders').update({status:s.value}).eq('id',s.dataset.id))}
function team(){view.innerHTML=`<section class="welcome"><p>إدارة الفريق</p><h2>إضافة الأعضاء<br>تتم بأمان من Supabase.</h2><ol><li>اذهب إلى <b>Authentication → Users</b> وأنشئ مستخدماً.</li><li>من SQL Editor أضف له سجل profile وحدد الدور: admin أو products أو orders.</li></ol></section>`}
start();
