const header = document.querySelector('.header');
const menu = document.querySelector('.menu-toggle');
menu.addEventListener('click', () => { const open = header.classList.toggle('open'); menu.setAttribute('aria-expanded', open); });
document.querySelectorAll('.nav a').forEach(a => a.addEventListener('click', () => header.classList.remove('open')));
document.querySelectorAll('.heart').forEach(button => button.addEventListener('click', () => { button.classList.toggle('saved'); button.textContent = button.classList.contains('saved') ? '♥' : '♡'; }));
const form = document.querySelector('form'); form.addEventListener('submit', e => { e.preventDefault(); const button = form.querySelector('button'); button.innerHTML = 'تم الاشتراك ✓'; form.querySelector('input').value = ''; });
const cart = []; const drawer = document.querySelector('.cart-drawer'), overlay = document.querySelector('.overlay');
const money = n => new Intl.NumberFormat('ar-SA').format(n) + ' ر.س';
function toggleCart(state=true){drawer.classList.toggle('open',state);overlay.classList.toggle('show',state);}
function renderCart(){const holder=document.querySelector('.cart-items'), count=document.querySelector('.bag em'), total=cart.reduce((a,p)=>a+p.price*p.qty,0);count.textContent=cart.reduce((a,p)=>a+p.qty,0); document.querySelector('.cart-total').textContent=money(total);holder.innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-row"><div class="mini-art ${p.category}"></div><div><b>${p.name}</b><small>${money(p.price)}</small><div class="quantity"><button data-i="${i}" data-change="-1">−</button><span>${p.qty}</span><button data-i="${i}" data-change="1">+</button></div></div><button class="remove" data-remove="${i}">×</button></div>`).join(''):`<div class="empty-cart"><span>♧</span><p>سلتك فارغة حالياً</p><button class="btn btn-dark drawer-close">ابدأ التسوق</button></div>`;}
document.querySelectorAll('.add-cart').forEach(btn=>btn.addEventListener('click',e=>{const p=e.currentTarget.closest('.product'), found=cart.find(x=>x.name===p.dataset.name);if(found)found.qty++;else cart.push({name:p.dataset.name,price:+p.dataset.price,category:p.dataset.category,qty:1});renderCart();toggleCart();}));
document.querySelector('.cart-open').onclick=()=>toggleCart();document.querySelectorAll('.drawer-close,.overlay').forEach(x=>x.onclick=()=>toggleCart(false));
document.querySelector('.cart-items').addEventListener('click',e=>{const i=e.target.dataset.i;if(e.target.dataset.remove!==undefined){cart.splice(e.target.dataset.remove,1)}if(i!==undefined){cart[i].qty+=+e.target.dataset.change;if(cart[i].qty<1)cart.splice(i,1)}renderCart();});
document.querySelector('.checkout').onclick=()=>alert('هذه نسخة تجريبية للمتجر. لربط الدفع والشحن نحتاج إعداد بوابة دفع وحسابات الشحن.');
document.querySelectorAll('.category-tabs button').forEach(b=>b.onclick=()=>{document.querySelector('.category-tabs .selected').classList.remove('selected');b.classList.add('selected');document.querySelectorAll('.product').forEach(p=>p.hidden=b.dataset.filter!=='all'&&p.dataset.category!==b.dataset.filter);});
const search=document.querySelector('.search-panel'), products=[...document.querySelectorAll('.product')];document.querySelector('.search-open').onclick=()=>search.classList.add('show');document.querySelector('.search-close').onclick=()=>search.classList.remove('show');search.querySelector('input').oninput=e=>{let q=e.target.value.trim();search.querySelector('.search-results').innerHTML=q?products.filter(p=>p.dataset.name.includes(q)).map(p=>`<button>${p.dataset.name}<span>${money(+p.dataset.price)}</span></button>`).join('')||'<p>لا توجد نتائج مطابقة</p>':'';};
